use_frameworks!

platform :ios, '11.0'

target 'Handy_Example' do
  pod 'Handy', :path => '../'
  pod 'SSZipArchive'
  pod 'MBProgressHUD'
  target 'Handy_Tests' do
    inherit! :search_paths

    
  end
end
